### PR TITLE
Feature/gulp upgrade

### PR DESCRIPTION
**Pull request by TriangleJuice**
Bearing in mind the increasing number of package vulnerabilities I upgraded the core branding to the latest version of gulp, which was the main cause of all these vulnerabilities.

In the process I also fixed some long-standing issues:

- Docs are now built correctly;
- Unnecessary build steps are skipped;
- When performing an `npm version [patch|minor|major]` docs are now automatically built and updated using the correct version number.

When approved, I will also send out PRs for the other branding packages.

### CODE REVIEW

**Comment by vademo** [comment]
- [ ] Update the changelog for version 3.3.0

**Comment by TriangleJuice** [comment]
This is only a technical update and did nothing to the actual output of the package.

**Comment by vademo** [comment]
The minor implies there are new features. A patch seems more correct int that case?

**Comment by TriangleJuice** [comment]
> The minor implies there are new features. A patch seems more correct in this case?

Discussed internally. Issue resolved.

**Pull request merged**
